// USER
export const LOGIN_USER = "LOGIN_USER";
export const REGISTER_USER = "REGISTER_USER";
export const FETCH_USER = "FETCH_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const DELETE_USER = "DELETE_USER";
export const USER_ERROR = "USER_ERROR";
export const UPDATE_USER = "UPDATE_USER";

// POST
export const POSTS_LOADED = "POSTS_LOADED";
export const POSTS_ERROR = "POSTS_ERROR";
export const POSTS_UNLOADED = "POSTS_UNLOADED";
export const ADD_POST = "ADD_POST";
export const UPDATE_POST = "UPDATE_POST";
export const DELETE_POST = "DELETE_POST";
export const POST_LOADED = "POST_LOADED";
export const POST_UNLOADED = "POST_UNLOADED";
export const POST_LOADING = "POST_LOADING";

//COMMENTS
export const COMMENTS_LOADED = "COMMENTS_LOADED";
export const COMMENTS_UNLOADED = "COMMENTS_UNLOADED";
export const DELETE_COMMENTS = "DELETE_COMMENTS";
export const POST_COMMENTS = "POST_COMMENTS";